from .manifests import ExperimentManifest, create_experiment_manifest, save_manifest_json
from .tables import export_m_matrix_csv, export_v_vector_csv, export_benchmark_table_csv
from .figures import (
    matplotlib_available,
    plot_m_matrix,
    plot_v_vector,
    plot_matching_failure_rates,
)
from .reports import make_markdown_research_report, make_latex_research_report
from .bundles import ReproducibilityBundle, create_reproducibility_bundle
from .runner import ResearchRunResult, run_research_platform_pipeline
from .cli import main

__all__ = [
    "ExperimentManifest",
    "create_experiment_manifest",
    "save_manifest_json",
    "export_m_matrix_csv",
    "export_v_vector_csv",
    "export_benchmark_table_csv",
    "matplotlib_available",
    "plot_m_matrix",
    "plot_v_vector",
    "plot_matching_failure_rates",
    "make_markdown_research_report",
    "make_latex_research_report",
    "ReproducibilityBundle",
    "create_reproducibility_bundle",
    "ResearchRunResult",
    "run_research_platform_pipeline",
    "main",
]


from .real_terms import (
    RealTermRegistryLoadResult,
    RealTermResearchRunResult,
    load_registry_for_research,
    export_term_audit_csv,
    make_real_term_validation_report,
    make_real_term_markdown_report,
    make_real_term_latex_report,
    run_real_term_research_pipeline,
)


from .captions import (
    FigureCaption,
    caption_for_m_matrix,
    caption_for_v_vector,
    caption_for_shot_scaling,
    caption_for_matching_failure,
    save_captions,
)
from .shot_scaling import (
    ShotScalingPoint,
    ShotScalingResult,
    run_single_workload_shot_scaling,
    export_shot_scaling_csv,
    plot_shot_scaling,
    run_endvqs_shot_scaling_package,
)
from .publication import (
    PublicationFigurePackage,
    build_publication_figure_package,
    make_publication_summary_report,
)


from .ibm_runtime import (
    IBMRuntimeConfig,
    IBMRuntimeDiagnosticsResult,
    IBMBackendSummary,
    IBMRuntimeSubmissionResult,
    ibm_runtime_packages_available,
    construct_qiskit_runtime_service,
    diagnose_ibm_runtime,
    list_ibm_backends,
    select_least_busy_backend,
    prepare_isa_circuit,
    build_ibm_demo_circuit,
    run_sampler_v2_job,
    run_estimator_v2_job,
    make_ibm_runtime_report,
    save_ibm_runtime_json,
    hardware_vs_simulator_comparison_scaffold,
)


from .hardware_compare import (
    CountsComparisonResult,
    ExpectationComparisonResult,
    BackendSnapshot,
    HardwareComparisonReportData,
    normalize_counts,
    total_variation_distance,
    compare_counts,
    compare_expectation_values,
    parse_counts_from_runtime_result,
    parse_estimator_value,
    retrieve_ibm_job_result,
    backend_snapshot_from_backend,
    save_backend_snapshot,
    save_counts_comparison_csv,
    plot_counts_comparison,
    make_hardware_comparison_markdown_report,
    make_hardware_comparison_latex_report,
    run_mock_hardware_comparison,
)


from .ibm_results import (
    IBMHardwareResult,
    make_service,
    get_latest_ibm_job_id,
    get_latest_job,
    get_job,
    get_backend_name_from_job,
    extract_sampler_counts,
    retrieve_ibm_hardware_result,
    get_latest_hardware_counts,
    save_counts_json,
    plot_counts,
    plot_latest_hardware_counts,
)


from .calibration_mitigation import (
    ReadoutMitigationMatrix,
    CalibrationSnapshot,
    MitigatedCountsResult,
    ZNEResult,
    MitigationReportData,
    readout_matrix_from_error,
    readout_matrices_from_calibration,
    project_to_probability_simple,
    mitigate_counts_readout,
    mitigated_probabilities_to_pseudo_counts,
    zero_noise_extrapolate,
    calibration_snapshot_from_backend_snapshot,
    mock_calibration_snapshot,
    save_calibration_snapshot,
    save_mitigated_probabilities_csv,
    plot_mitigated_probabilities,
    plot_zne,
    make_mitigation_markdown_report,
    make_mitigation_latex_report,
    run_mitigation_workflow_from_counts,
    run_mock_mitigation_workflow,
    run_latest_hardware_mitigation_workflow,
)


from .uncertainty import (
    ConfidenceInterval,
    BitstringUncertainty,
    CountsUncertaintyResult,
    ExpectationUncertaintyResult,
    DifferenceUncertaintyResult,
    UncertaintyReportData,
    binomial_standard_error,
    wilson_confidence_interval,
    counts_uncertainty,
    counts_to_samples,
    expectation_from_counts,
    bootstrap_expectation_uncertainty,
    propagate_difference_uncertainty,
    parity_observable_map,
    export_counts_uncertainty_csv,
    export_expectation_uncertainty_csv,
    plot_counts_uncertainty,
    make_uncertainty_markdown_report,
    make_uncertainty_latex_report,
    run_mock_uncertainty_workflow,
)


from .experiment_db import (
    ArtifactRecord,
    BackendMetadataRecord,
    ExperimentRunRecord,
    ExperimentDatabase,
    new_run_record,
    artifact_from_path,
    backend_record_from_hardware_result,
    record_from_dict,
    export_run_table_csv,
    export_dashboard_json,
    summarize_records,
    make_run_database_report,
    index_artifacts_from_directory,
    create_demo_run_database,
)


from .dashboard import (
    MetricTrendPoint,
    MetricTrendResult,
    BackendHistoryEntry,
    DashboardPackage,
    collect_metric_trend,
    export_metric_trend_csv,
    plot_metric_trend,
    backend_performance_history,
    export_backend_history_csv,
    collect_artifacts,
    export_artifact_index_csv,
    make_artifact_browser_html,
    make_dashboard_html,
    make_dashboard_markdown_report,
    build_dashboard_package,
)


from .job_sync import (
    JobSyncResult,
    DatabaseSyncSummary,
    normalize_job_status,
    is_success_status,
    is_failure_status,
    is_pending_status,
    get_job_ids_from_records,
    update_record_status,
    mock_job_payload,
    sync_job_from_payload,
    sync_ibm_job,
    sync_database_with_payloads,
    export_sync_results_csv,
    make_sync_markdown_report,
    run_mock_sync_workflow,
    run_mock_failure_sync_workflow,
)


from .project_config import (
    WorkflowSettings,
    HardwareSettings,
    AZMQOSProjectConfig,
    default_project_config,
    project_config_from_dict,
    load_project_config,
    save_project_config,
    init_project,
    validate_project_config,
)
from .plugin_registry import (
    ComponentPluginRecord,
    PluginRegistry,
    default_plugin_registry,
    save_plugin_registry,
    load_plugin_registry,
    make_plugin_registry_report,
)
from .app import (
    IntegratedWorkflowResult,
    make_manuscript_scaffold,
    make_project_summary_report,
    create_final_archive,
    run_integrated_workflow,
)


from .production import (
    ObservableSelection,
    ExecutionPolicy,
    QueuePolicy,
    ManuscriptSettings,
    ProductionProjectSpec,
    ProductionPlanItem,
    ProductionPlan,
    ProductionRunResult,
    production_spec_from_dict,
    load_production_spec,
    save_production_spec,
    init_production_project,
    validate_production_spec,
    infer_component_family,
    select_components_from_registry,
    make_production_plan,
    export_production_plan_json,
    export_production_plan_csv,
    make_production_plan_report,
    make_resume_manifest,
    make_production_manuscript_scaffold,
    create_production_archive,
    run_production_dry_run,
)


from .production_execution import (
    WorkloadSpec,
    ExecutionResult,
    JobManifest,
    ProductionExecutionBatchResult,
    classify_measurement_type,
    plan_item_to_workload,
    production_plan_to_workloads,
    make_job_manifest,
    simulate_workload_result,
    run_simulator_batch,
    run_hardware_dry_run_batch,
    export_job_manifest_json,
    export_workloads_csv,
    export_execution_results_json,
    export_execution_results_csv,
    attach_results_to_production_database,
    make_execution_report,
    run_production_execution_adapter,
)


from .production_simulator import (
    CircuitSpec,
    SimulatorExecutionConfig,
    SimulatorComparisonResult,
    ShotScalingPoint,
    ProductionSimulatorBatchResult,
    workload_to_rotation_angle,
    workload_to_circuit_spec,
    circuit_spec_to_qiskit,
    exact_expectation_from_circuit_spec,
    exact_probabilities_from_circuit_spec,
    expectation_from_binary_counts,
    run_fallback_simulator,
    run_aer_simulator,
    run_simulator_for_circuit,
    compare_simulator_to_exact,
    run_production_simulator_batch,
    export_circuit_specs_json,
    export_simulator_comparisons_csv,
    plot_simulator_comparisons,
    attach_simulator_results_to_database,
    make_simulator_report,
    run_shot_scaling_for_workload,
    run_production_shot_scaling,
    export_shot_scaling_points_csv,
    plot_shot_scaling_points,
)


from .pauli_compiler import (
    PauliTerm,
    PauliComponent,
    CommutingGroup,
    MeasurementCircuitSpec,
    HadamardTestSpec,
    PauliCompilationResult,
    parse_complex,
    pauli_term_from_dict,
    pauli_component_from_dict,
    load_pauli_components_from_registry,
    pauli_commutes,
    can_share_single_qubit_measurement_basis,
    merge_measurement_basis,
    group_commuting_terms_greedy,
    basis_rotations_for_pauli_basis,
    measurement_circuit_spec_from_group,
    measurement_spec_to_qiskit,
    make_hadamard_test_specs,
    hadamard_test_spec_to_qiskit,
    bitstring_eigenvalue_for_pauli,
    expectation_from_counts_for_pauli,
    component_expectation_from_group_counts,
    ancilla_expectation_from_counts,
    compile_pauli_component,
    compile_registry_components,
    export_pauli_component_json,
    export_commuting_groups_json,
    export_measurement_specs_json,
    export_hadamard_specs_json,
    make_pauli_compilation_report,
    make_pauli_compile_demo,
)


from .production_pauli_execution import (
    GroupedMeasurementResult,
    ComponentEstimateResult,
    ProductionPauliExecutionResult,
    qubit_expectations_for_basis,
    exact_group_expectation_for_pauli,
    deterministic_counts_for_basis,
    execute_commuting_group,
    reconstruct_component_estimate,
    execute_component_pauli_measurements,
    load_selected_pauli_components,
    export_grouped_counts_json,
    export_component_estimates_csv,
    export_grouped_counts_csv,
    export_mv_estimate_tables,
    plot_component_estimates,
    attach_pauli_estimates_to_database,
    make_mv_estimate_report,
    make_production_pauli_execution_report,
    run_production_pauli_execution,
)


from .qiskit_pauli_execution import (
    QiskitExecutionConfig,
    QiskitCircuitBuildResult,
    QiskitGroupExecutionResult,
    QiskitComponentExecutionResult,
    ProductionQiskitExecutionResult,
    qiskit_is_available,
    build_qiskit_measurement_circuit,
    build_circuit_or_fallback_spec,
    normalize_qiskit_counts,
    run_qiskit_circuit_counts,
    hardware_dry_run_transpile_scaffold,
    term_expectations_from_counts,
    execute_group_with_qiskit_or_fallback,
    execute_component_with_qiskit_or_fallback,
    export_qiskit_group_results_json,
    export_qiskit_group_results_csv,
    export_circuit_builds_json,
    make_qiskit_execution_report,
    run_production_qiskit_execution,
)


from .endvqs_stateprep import (
    ElectronicStateParameters,
    NuclearCoherentParameters,
    ENDVQSLayout,
    ENDVQSStatePreparationConfig,
    StatePreparationOperation,
    StatePreparationPlan,
    ENDVQSExecutionResult,
    electronic_params_from_dict,
    nuclear_params_from_dict,
    layout_from_dict,
    stateprep_config_from_dict,
    load_stateprep_config,
    save_stateprep_config,
    make_fukutome_electronic_operations,
    make_nuclear_coherent_operations,
    derivative_operations,
    make_endvqs_stateprep_plan,
    apply_stateprep_operations_to_qiskit,
    make_qiskit_stateprep_hook,
    make_derivative_stateprep_config,
    infer_derivative_for_component,
    make_component_specific_stateprep_plan,
    export_stateprep_plan_json,
    export_stateprep_operations_csv,
    make_stateprep_report,
    make_stateprep_demo,
    run_endvqs_qiskit_component_execution,
    run_production_endvqs_execution,
    export_endvqs_execution_results_csv,
    export_endvqs_execution_results_json,
    make_endvqs_execution_report,
)


from .derivative_estimators import (
    DerivativeParameter,
    DerivativeEstimatorConfig,
    ComponentDerivativeEstimate,
    ProductionDerivativeResult,
    derivative_parameters_from_dicts,
    get_parameter_vector,
    get_parameter_value,
    set_parameter_value,
    shifted_stateprep_config,
    component_family,
    evaluate_component_value,
    estimate_uncertainty_from_values,
    estimate_component_derivative,
    estimate_component_derivatives,
    export_derivative_estimates_csv,
    export_derivative_estimates_json,
    export_derivative_summary_tables,
    plot_derivative_comparison,
    make_derivative_report,
    run_derivative_demo,
    run_production_derivative_estimators,
)


from .derivative_mitigation import (
    ReadoutCalibration,
    ZNEConfig,
    MitigatedDerivativeEstimate,
    ProductionDerivativeMitigationResult,
    default_single_qubit_calibration,
    invert_2x2,
    apply_readout_mitigation_to_binary_probs,
    mitigate_expectation_value,
    mitigate_derivative_readout,
    synthetic_noise_scaled_derivatives,
    linear_zne_extrapolate,
    zne_derivative_estimate,
    propagate_derivative_uncertainty,
    allocate_derivative_shots,
    mitigate_derivative_estimate,
    mitigate_derivative_estimates,
    export_mitigated_derivatives_csv,
    export_mitigated_derivatives_json,
    export_mitigated_mv_tables,
    plot_mitigated_derivative_comparison,
    make_derivative_mitigation_report,
    run_derivative_mitigation_demo,
    run_production_mitigated_derivatives,
)


from .stable_platform import (
    StableWorkflowResult,
    ensure_production_config,
    make_stable_manuscript_scaffold,
    make_stable_report,
    create_stable_archive,
    run_stable_workflow,
    run_stable_smoke_test,
)


from .qec_logical import (
    StabilizerCodeSpec,
    LogicalPauliTerm,
    LogicalPauliComponent,
    SyndromeMeasurementSpec,
    LogicalObservableEstimate,
    ProductionQECResult,
    normalize_pauli_string,
    default_repetition_code,
    default_five_qubit_code,
    get_code_by_name,
    pauli_product_char,
    pauli_product_ignore_phase,
    map_single_logical_pauli_to_physical,
    map_logical_pauli_string_to_physical,
    map_pauli_term_to_logical,
    map_component_to_logical,
    make_syndrome_specs,
    syndrome_acceptance_probability,
    deterministic_logical_expectation,
    estimate_logical_component,
    load_selected_components_for_qec,
    export_logical_components_json,
    export_syndrome_specs_json,
    export_logical_estimates_csv,
    export_logical_estimates_json,
    export_qec_mv_tables,
    plot_logical_estimates,
    attach_qec_estimates_to_database,
    make_qec_report,
    run_qec_demo,
    run_production_qec_estimator,
)


from .qec_decoder import (
    SyndromeSample,
    DecoderResult,
    DecodedLogicalEstimate,
    ProductionQECDecoderResult,
    repetition_syndrome_for_error,
    repetition_lookup_table,
    decode_repetition_syndrome,
    apply_repetition_correction,
    simulate_syndrome_samples,
    decode_syndrome_samples,
    binomial_uncertainty,
    decoded_estimate_from_logical_estimate,
    export_syndrome_samples_csv,
    export_decoder_results_csv,
    export_decoded_estimates_csv,
    export_decoded_estimates_json,
    export_decoded_mv_tables,
    plot_decoded_estimates,
    attach_decoded_estimates_to_database,
    make_qec_decoder_report,
    run_qec_decoder_demo,
    run_production_qec_decoder,
)


from .qec_fault_tolerant import (
    CircuitNoiseModel,
    SyndromeExtractionCircuitSpec,
    SyndromeRoundResult,
    FaultTolerantComponentResult,
    DecoderComparisonSummary,
    ProductionFTQECResult,
    make_syndrome_extraction_circuit_spec,
    make_repeated_syndrome_schedule,
    syndrome_spec_to_qiskit,
    effective_round_error_probability,
    simulate_repeated_syndrome_rounds,
    estimate_logical_failure_rate,
    ft_correct_decoded_estimate,
    make_decoder_comparison,
    export_syndrome_circuit_specs_json,
    export_ft_component_results_csv,
    export_ft_component_results_json,
    export_decoder_comparisons_csv,
    export_ft_mv_tables,
    plot_ft_qec_results,
    attach_ft_qec_to_database,
    make_ft_qec_report,
    run_ft_qec_demo,
    run_production_ft_qec,
)


from .qec_hardware import (
    BackendTargetSpec,
    CircuitResourceSummary,
    ISACheckResult,
    LayoutRecommendation,
    HardwareDryRunJobManifest,
    ProductionQECHardwareResult,
    qiskit_available,
    default_backend_target,
    resource_summary_from_spec,
    transpile_syndrome_spec_dry_run,
    check_isa_constraints,
    recommend_noise_aware_layout,
    make_hardware_dry_run_job_manifest,
    export_resource_summaries_csv,
    export_json_dataclasses,
    export_isa_checks_csv,
    export_job_manifests_csv,
    plot_resource_summaries,
    attach_hardware_dry_run_to_database,
    make_qec_hardware_report,
    run_qec_hardware_demo,
    run_production_qec_hardware_dry_run,
)


from .qec_hardware_sync import (
    HardwareJobReference,
    HardwareCountsRecord,
    HardwareSyncComparison,
    ProductionHardwareSyncResult,
    normalize_counts,
    counts_to_probabilities,
    total_variation_distance,
    dominant_outcome,
    job_reference_from_manifest,
    job_references_from_manifests,
    parse_job_ids_file,
    synthetic_hardware_counts_for_job,
    parse_counts_file,
    expected_dry_run_counts,
    compare_dry_run_to_hardware,
    sync_hardware_results,
    export_job_references_csv,
    export_counts_records_csv,
    export_sync_comparisons_csv,
    make_hardware_sync_report,
    run_qec_hardware_sync_demo,
    run_production_qec_hardware_sync,
)


from .qec_runtime_fetch import (
    RuntimeFetchConfig,
    RuntimeJobStatusRecord,
    RuntimeFetchRecord,
    RuntimeSyncResult,
    runtime_package_available,
    make_runtime_service,
    cache_key_for_job,
    cache_path_for_job,
    load_cached_fetch_record,
    save_fetch_record_to_cache,
    fetch_runtime_job_status,
    fetch_runtime_counts,
    fetch_job_with_retry,
    fetch_jobs_with_runtime_adapter,
    export_runtime_fetch_records_csv,
    export_runtime_fetch_records_json,
    attach_runtime_sync_to_database,
    make_runtime_sync_report,
    run_runtime_fetch_demo,
    run_production_runtime_sync,
)


from .qec_hardware_analysis import (
    BackendCalibrationMetadata,
    HardwareRunSummary,
    CountsConfidenceInterval,
    LogicalFailureConfidenceBand,
    HardwareAnalysisResult,
    wilson_interval,
    load_backend_calibration,
    default_calibration_metadata,
    classify_fetch_source,
    make_hardware_run_summary,
    make_counts_confidence_intervals,
    make_failure_bands_from_comparisons,
    export_run_summary_json,
    export_calibration_json,
    export_counts_intervals_csv,
    export_failure_bands_csv,
    plot_failure_bands,
    plot_real_vs_synthetic_summary,
    make_hardware_analysis_report,
    attach_hardware_analysis_to_database,
    create_final_qec_experiment_archive,
    analyze_runtime_sync_result,
    run_hardware_analysis_demo,
    run_production_hardware_analysis,
)


from .qec_final_export import (
    FinalFigureRecord,
    ReproducibilityChecklist,
    VersionLockfile,
    FinalExportResult,
    read_package_version,
    collect_project_artifacts,
    copy_final_figures,
    make_summary_figure_from_artifacts,
    make_latex_manuscript_scaffold,
    make_thesis_appendix_scaffold,
    make_final_command_summary,
    make_reproducibility_checklist,
    export_reproducibility_checklist,
    make_version_lockfile,
    export_version_lockfile,
    make_final_export_report,
    create_final_project_archive,
    export_json_dataclasses,
    run_final_export_from_analysis,
    run_final_export_demo,
    run_production_final_export,
)


from .qec_release import (
    ReleaseValidationIssue,
    ReleaseValidationReport,
    ReleasePackageResult,
    required_final_artifact_keys,
    validate_final_export_artifacts,
    export_validation_report,
    make_clean_command_table,
    make_windows_troubleshooting_guide,
    make_html_final_report,
    create_minimal_release_package,
    make_release_manifest,
    run_release_packaging_from_final_export,
    run_production_release,
    run_release_demo,
    run_minimal_package_demo,
)


from .qec_public_release import (
    PUBLIC_VERSION,
    PUBLIC_RELEASE_NAME,
    PublicReleaseManifest,
    APIReferenceEntry,
    PublicReleaseValidation,
    make_public_release_manifest,
    export_public_release_manifest,
    build_api_reference_entries,
    export_api_reference_markdown,
    export_docs_site_scaffold,
    export_paper_reproduction_index,
    export_scaffold_label_cleanup_report,
    export_citation_metadata,
    validate_public_release,
    export_public_validation_report,
    run_public_release_info,
    run_public_release_validate,
)
