from __future__ import annotations
from pathlib import Path
import numpy as np

def make_markdown_research_report(result, path):
    path = Path(path)
    M = np.asarray(result.M)
    V = np.asarray(result.V)

    lines = [
        "# AZM-QOS v2.0 Research Report",
        "",
        "## Manifest",
        "",
        "```text",
        result.manifest.summary(),
        "```",
        "",
        "## END/VQS Results",
        "",
        "### M matrix",
        "",
        "```text",
        str(M),
        "```",
        "",
        "### V vector",
        "",
        "```text",
        str(V),
        "```",
        "",
        "## Detector Error Model",
        "",
        "```text",
        result.detector_error_model.summary(),
        "```",
        "",
        "## Matching Benchmark",
        "",
        "```text",
        result.matching_benchmark_result.summary(),
        "```",
        "",
        "## Artifacts",
        "",
    ]

    for name, artifact_path in result.artifacts.items():
        lines.append(f"- **{name}**: `{artifact_path}`")

    lines.extend([
        "",
        "## Scientific note",
        "",
        "This v2.0 run uses the current AZM-QOS configured terms. If proxy END/VQS terms are still present, replace them with derived Pauli decompositions before using the output as final research data.",
        "",
    ])

    text = "\n".join(lines)
    path.write_text(text, encoding="utf-8")
    return path

def make_latex_research_report(result, path):
    path = Path(path)
    M = np.asarray(result.M)
    V = np.asarray(result.V)

    def matrix_to_latex(A):
        rows = []
        for row in A:
            rows.append(" & ".join(f"{float(x):.6f}" for x in row))
        return "\\n".join(rows)

    def vector_to_latex(v):
        return " & ".join(f"{float(x):.6f}" for x in v.reshape(-1))

    tex = r"""
\documentclass[11pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{hyperref}
\title{AZM-QOS v2.0 Reproducible Research Report}
\author{AZM-QOS Automated Research Platform}
\date{\today}
\begin{document}
\maketitle

\begin{abstract}
This report was generated by AZM-QOS v2.0. The workflow combines END/VQS observable assembly, detector-error-model generation, matching-decoder benchmarking, experiment manifests, and reproducibility artifacts.
\end{abstract}

\section{Experiment Manifest}
\begin{verbatim}
""" + result.manifest.summary() + r"""
\end{verbatim}

\section{END/VQS Results}
The assembled matrix $M$ is
\[
M =
\begin{bmatrix}
""" + matrix_to_latex(M) + r"""
\end{bmatrix}.
\]
The assembled vector $V$ is
\[
V =
\begin{bmatrix}
""" + vector_to_latex(V) + r"""
\end{bmatrix}.
\]

\section{Detector Error Model}
\begin{verbatim}
""" + result.detector_error_model.summary() + r"""
\end{verbatim}

\section{Matching Benchmark}
\begin{verbatim}
""" + result.matching_benchmark_result.summary() + r"""
\end{verbatim}

\section{Artifacts}
The run generated machine-readable CSV, JSON, figure, and report artifacts listed in the experiment manifest.

\section{Limitations}
If the current END/VQS registry still contains proxy terms, the numerical values are architecture-validation data rather than final scientific results. Replace proxy terms with derived Pauli decompositions before using the results in a final manuscript.

\end{document}
"""
    path.write_text(tex.strip() + "\n", encoding="utf-8")
    return path
